### ISSUE TITLE
Add a bootstrap linter

### ISSUE THREAD

**Issue by critmcdonald** [utdata/icj-project-rig#37]
A bootstrap linter would help students know when they've done their HTML incorrectly. An alternative might be one in VS Code?

**Comment by critmcdonald** [comment]
I'm not so sure about this. I tried it in the bootlint branch. Beyond not being able to get it to work in the default gulp talk the linting was so strict it showed errors that clearly kosher in the bootstrap documentation.

**Comment by michplunkett** [comment]
If you'd like, I could add a GitHub action that does not let anything be merged UNLESS it is correctly formatted and linted.

**Comment by michplunkett** [comment]
Added to this PR: https://github.com/utdata/icj-project-rig/pull/89
