### ISSUE TITLE
Import assertions not stable

### ISSUE THREAD

**Issue by critmcdonald** [utdata/icj-project-rig#87]
I get the following warning when I run npm install:

> (node:3013) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.

I think these were added by Mandi in the last rig update. #79 . The link to the reasons listed there are now 404.

**Comment by critmcdonald** [comment]
This _might_ be useful? https://simonplend.com/import-json-in-es-modules/

**Comment by critmcdonald** [comment]
I tried this method:

```
const config = await import("../project.config.json", {
  assert: { type: "json" },
});
```
and it would not work in the nunjucks task. Seemed to work fine in the bake task.

**Comment by michplunkett** [comment]
Addressed in this PR: https://github.com/utdata/icj-project-rig/pull/89
